version: "3.9"
services:
  mv-font-suivi-evaluation:
    container_name: mv-front-suivi-evaluation
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    networks:
      - mv-docker-network
    command: npm run start
    expose:
      - 3000
networks:
  mv-docker-network:
    name: mv-docker-network
    